/* LDC SEARCH-V2.2 A9 — deterministic textual near-quotation retrieval.
   Governing label: Formulation proche. Never exact, never semantic.
   Browser/Worker: globalThis.LDCSearchNearV22. Node: module.exports. */
(function(root,factory){
  const core=(root&&root.LDCSearchV2)||(typeof require==='function'?require('./search_engine_v2.js'):null);
  const api=factory(core);
  if(typeof module==='object'&&module.exports)module.exports=api;
  if(root)root.LDCSearchNearV22=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(Core){
'use strict';
if(!Core)throw new Error('SEARCH-V2.2 requires SEARCH-V2 core');
const VERSION='ldc-search-v22-a9-r1';
const VALID_MODES=new Set(['aflp','additions','enriched']);
const STRONG=new Set(['pas','jamais','rien','aucun','aucune','sans','ni','non']);
const PROTECTED={
  agency_person:new Set(['je','j','me','m','moi','tu','te','t','toi','il','elle','lui','nous','vous','ils','elles','mon','ma','mes','ton','ta','tes','son','sa','ses','notre','nos','votre','vos','leur','leurs']),
  modality:new Set(['peux','peut','pouvons','pouvez','peuvent','pourrais','pourrait','pourrions','pourriez','pourraient','dois','doit','devons','devez','doivent','devrais','devrait','devrions','devriez','devraient','veux','veut','voulons','voulez','veulent','voudrais','voudrait','voudrions','voudriez','voudraient','faut','fallait','faudrait']),
  theological_entity:new Set(['dieu','jesus','seigneur','pere','fils','esprit','marie','vierge','divine','volonte'])
};
function qtokens(s){const n=Core.normalise(String(s==null?'':s).normalize('NFC'));return n?n.split(' ').filter(Boolean):[];}
function threshold(q){return q.length<=5?1:2;}
function charLev(a,b,max=99){if(Math.abs(a.length-b.length)>max)return max+1;let prev=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const cur=[i];for(let j=1;j<=b.length;j++)cur[j]=Math.min(prev[j]+1,cur[j-1]+1,prev[j-1]+(a[i-1]===b[j-1]?0:1));prev=cur;}return prev[b.length];}
function align(q,s){const n=q.length,m=s.length;let prev=Array.from({length:m+1},(_,j)=>({ops:j,w:j})),prev2=null;for(let i=1;i<=n;i++){const cur=Array(m+1);cur[0]={ops:i,w:i};for(let j=1;j<=m;j++){let o=0,w=0;if(q[i-1]!==s[j-1]){o=1;const cd=charLev(q[i-1],s[j-1],2),mx=Math.max(q[i-1].length,s[j-1].length);w=cd===1?.35:(cd===2&&mx>7?.70:1);}let z={ops:prev[j-1].ops+o,w:prev[j-1].w+w};let z2={ops:prev[j].ops+1,w:prev[j].w+1};if(z2.ops<z.ops||(z2.ops===z.ops&&z2.w<z.w))z=z2;z2={ops:cur[j-1].ops+1,w:cur[j-1].w+1};if(z2.ops<z.ops||(z2.ops===z.ops&&z2.w<z.w))z=z2;if(i>1&&j>1&&q[i-1]===s[j-2]&&q[i-2]===s[j-1]){z2={ops:prev2[j-2].ops+1,w:prev2[j-2].w+.65};if(z2.ops<z.ops||(z2.ops===z.ops&&z2.w<z.w))z=z2;}cur[j]=z;}prev2=prev;prev=cur;}return prev[m];}
function osaBounded(q,toks,st,L,E){const n=q.length,m=L;if(Math.abs(n-m)>E)return E+1;let prev=Array.from({length:m+1},(_,j)=>j),prev2=null;for(let i=1;i<=n;i++){const cur=Array(m+1);cur[0]=i;for(let j=1;j<=m;j++){let v=Math.min(prev[j]+1,cur[j-1]+1,prev[j-1]+(q[i-1]===toks[st+j-1]?0:1));if(i>1&&j>1&&q[i-1]===toks[st+j-2]&&q[i-2]===toks[st+j-1])v=Math.min(v,prev2[j-2]+1);cur[j]=v;}prev2=prev;prev=cur;}return prev[m];}
function alignWindow(q,toks,st,L){const n=q.length,m=L;let prev=Array.from({length:m+1},(_,j)=>({ops:j,w:j})),prev2=null;for(let i=1;i<=n;i++){const cur=Array(m+1);cur[0]={ops:i,w:i};for(let j=1;j<=m;j++){const sv=toks[st+j-1];let o=0,w=0;if(q[i-1]!==sv){o=1;const cd=charLev(q[i-1],sv,2),mx=Math.max(q[i-1].length,sv.length);w=cd===1?.35:(cd===2&&mx>7?.70:1);}let z={ops:prev[j-1].ops+o,w:prev[j-1].w+w};let z2={ops:prev[j].ops+1,w:prev[j].w+1};if(z2.ops<z.ops||(z2.ops===z.ops&&z2.w<z.w))z=z2;z2={ops:cur[j-1].ops+1,w:cur[j-1].w+1};if(z2.ops<z.ops||(z2.ops===z.ops&&z2.w<z.w))z=z2;if(i>1&&j>1&&q[i-1]===toks[st+j-2]&&q[i-2]===sv){z2={ops:prev2[j-2].ops+1,w:prev2[j-2].w+.65};if(z2.ops<z.ops||(z2.ops===z.ops&&z2.w<z.w))z=z2;}cur[j]=z;}prev2=prev;prev=cur;}return prev[m];}
function polSig(t){const s=new Set(t.filter(x=>STRONG.has(x)));for(let i=0;i<t.length;i++)if(t[i]==='ne'||t[i]==='n'){for(let j=i+1;j<=Math.min(t.length-1,i+3);j++){if(t[j]==='plus')s.add('NE_PLUS');else if(t[j]==='personne')s.add('NE_PERSONNE');else if(t[j]==='guere')s.add('NE_GUERE');}}return [...s].sort().join('|');}
function multiset(tokens,set){const m=new Map();for(const t of tokens)if(set.has(t))m.set(t,(m.get(t)||0)+1);return [...m.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(x=>x.join(':')).join('|');}
function criticalDiff(q,s){const out=[];for(const [name,set] of Object.entries(PROTECTED))if(multiset(q,set)!==multiset(s,set))out.push(name);return out;}
function leftBoundary(s,anchor,n){let pos=anchor,moved=0;while(moved<n&&pos>0){const prev=s.lastIndexOf(' ',pos-2);pos=prev+1;moved++;}return{pos,moved};}
function rightBoundary(s,anchorEnd,nTokensIncl){let pos=anchorEnd,count=1;while(count<nTokensIncl&&pos<s.length){if(s.charCodeAt(pos)===32)pos++;const sp=s.indexOf(' ',pos);if(sp===-1){pos=s.length;count++;break;}pos=sp;count++;}return pos;}
function occurrences(s,t){const out=[];let from=0,at;while((at=s.indexOf(t,from))!==-1){const en=at+t.length;if((at===0||s.charCodeAt(at-1)===32)&&(en===s.length||s.charCodeAt(en)===32))out.push(at);from=at+1;}return out;}
function overlapLen(a,b){return Math.max(0,Math.min(a.end,b.end)-Math.max(a.start,b.start));}
function dominatesConflict(safe,conf){const ov=overlapLen(safe,conf);if(!ov)return false;const ml=Math.min(safe.end-safe.start,conf.end-conf.start);if(ov*2<ml)return false;return conf.ops<safe.ops||(conf.ops===safe.ops&&conf.w<=safe.w+1e-12);}
function better(a,b){if(!a)return b;if(!b)return a;if(b.ops!==a.ops)return b.ops<a.ops?b:a;if(Math.abs(b.w-a.w)>1e-12)return b.w<a.w?b:a;if(b.critical_count!==a.critical_count)return b.critical_count<a.critical_count?b:a;return a;}
function streamTokenStarts(stream){if(!stream)return[];const out=[0];for(let i=0;i<stream.length;i++)if(stream.charCodeAt(i)===32)out.push(i+1);return out;}
function tokenIndexAt(starts,charPos){let lo=0,hi=starts.length-1;while(lo<=hi){const mid=(lo+hi)>>1,v=starts[mid];if(v===charPos)return mid;if(v<charPos)lo=mid+1;else hi=mid-1;}return -1;}
function sourceParts(tokens,documents){const out=[];for(const t of tokens){const d=documents[t.di],last=out[out.length-1];if(last&&last.doc_index===t.di&&last.atom_index===t.atom_index){last.canonical_end=Math.max(last.canonical_end,t.e);last.token_count++;}else out.push({doc_index:t.di,id:d[0],para_id:d[0],stable_ref:d[4],canonical_start:t.s,canonical_end:t.e,source_kind:d[3]===1?'supplement':(String(d[0]).includes('_editorial_')?'editorial':'principal'),token_count:1,atom_index:t.atom_index});}return out.map(({atom_index,...p})=>p);}
function createNearLayer(payload){
  const index=payload.index,documents=payload.documents.documents,entries=payload.entries.entries,top=payload.topology,exact=payload.exact;
  if(!index||!documents||!entries||!top||!exact||!exact.nearAuthority)throw new Error('SEARCH-V2.2 incomplete authority payload');
  const authority=exact.nearAuthority, entryById=new Map(entries.map((e,i)=>[String(e[0]),i]));
  const modeUnits={};for(const mode of VALID_MODES)modeUnits[mode]=authority.units(mode).map((u,i)=>({...u,_ui:i}));
  const unitById={};for(const mode of VALID_MODES)unitById[mode]=new Map(modeUnits[mode].map(u=>[u.id,u]));
  const df={};const shortTf={};
  for(const mode of VALID_MODES){const dm=new Map(),sm=new Map();for(const u of modeUnits[mode]){const toks=u.stream?u.stream.split(' '):[],seen=new Set(),sc=new Map();for(const t of toks){if(!seen.has(t)){seen.add(t);dm.set(t,(dm.get(t)||0)+1);}if(t.length<=2)sc.set(t,(sc.get(t)||0)+1);}for(const[t,tf]of sc){let a=sm.get(t);if(!a)sm.set(t,a=[]);a.push([u._ui,tf]);}}df[mode]=dm;shortTf[mode]=sm;}
  function atomDi(a){return Number.isInteger(a)?a:a[0];}
  function docToUnits(mode){const out=new Int32Array(documents.length);out.fill(-1);const idToUi=new Map(modeUnits[mode].map(u=>[u.id,u._ui]));if(mode==='aflp'){for(const r of top.base_units||[]){const ui=idToUi.get('P:'+r[0]);for(const a of r[4]||[])out[atomDi(a)]=ui;}}else if(mode==='additions'){for(const r of top.complement_units||[]){const ui=idToUi.get(String(r[0]));for(const a of r[6]||[])out[atomDi(a)]=ui;}}else{const over=new Map((top.enriched_overrides||[]).map(r=>[r[0],r[1]]));for(const r of top.base_units||[]){const ui=idToUi.get('P:'+r[0]);for(const a of over.get(r[0])||r[4]||[])out[atomDi(a)]=ui;}for(const r of top.complete_units||[]){const ui=idToUi.get(String(r[0]));for(const a of r[6]||[])out[atomDi(a)]=ui;}}return out;}
  const docToUnit={};for(const mode of VALID_MODES)docToUnit[mode]=docToUnits(mode);
  const postingCache=new Map();function posting(t){if(!postingCache.has(t))postingCache.set(t,index.terms&&index.terms[t]?Core.decodePosting(index.terms[t]):[]);return postingCache.get(t);}
  function candidateUnits(mode,q,E){const us=modeUnits[mode],score=new Uint16Array(us.length),qc=new Map();for(const t of q)qc.set(t,(qc.get(t)||0)+1);for(const[t,nq]of qc){if(t.length<=2){for(const[ui,tf]of shortTf[mode].get(t)||[])score[ui]+=Math.min(nq,tf);}else{const tfu=new Map();for(const[di,tf]of posting(t)){const ui=docToUnit[mode][di];if(ui>=0)tfu.set(ui,(tfu.get(ui)||0)+tf);}for(const[ui,tf]of tfu)score[ui]+=Math.min(nq,tf);}}const need=q.length-E,out=[];for(let ui=0;ui<score.length;ui++)if(score[ui]>=need)out.push(ui);return out;}
  function anchors(mode,q,E){return q.map((t,i)=>({t,i,df:Number(df[mode].get(t)||0)})).sort((a,b)=>a.df-b.df||a.i-b.i).slice(0,E+1);}
  function bestInUnit(u,q,E,ans,opt){
    const qs=polSig(q),wins=[],seen=new Set(),toks=u.stream?u.stream.split(' '):[];if(!toks.length)return null;
    const starts=new Array(toks.length);let cp=0;for(let i=0;i<toks.length;i++){starts[i]=cp;cp+=toks[i].length+1;}
    const amap=new Map();for(const an of ans){let a=amap.get(an.t);if(!a)amap.set(an.t,a=[]);a.push(an);}
    for(let at=0;at<toks.length;at++){const al=amap.get(toks[at]);if(!al)continue;for(const an of al){for(let delta=-E;delta<=E;delta++){const st=at-an.i+delta;for(let L=Math.max(1,q.length-E);L<=q.length+E;L++){if(st<0||st+L>toks.length)continue;const key=st+'|'+L;if(seen.has(key))continue;seen.add(key);const od=osaBounded(q,toks,st,L,E);if(od===0||od>E)continue;const a=alignWindow(q,toks,st,L);if(a.ops===0||a.ops>E)continue;const win=toks.slice(st,st+L),classes=criticalDiff(q,win),start=starts[st],end=starts[st+L-1]+toks[st+L-1].length;wins.push({ops:a.ops,w:a.w,critical_count:classes.length,critical_classes:classes,window:win.join(' '),polarity:polSig(win),start,end,token_len:L,global_start:st});}}}}
    const safe=wins.filter(x=>x.polarity===qs),conf=wins.filter(x=>x.polarity!==qs);let best=null,canonicalTokens=null;
    for(const rec of safe){if(conf.some(c=>dominatesConflict(rec,c)))continue;if(opt.jesus){if(!canonicalTokens)canonicalTokens=authority.tokens(opt.mode,u.id);if(!authority.touchesJesus(canonicalTokens.slice(rec.global_start,rec.global_start+rec.token_len)))continue;}best=better(best,rec);}return best;
  }
  function scopeAllows(u,p,opt){if(opt.volMin&&u.volume<opt.volMin)return false;if(opt.volMax&&u.volume>opt.volMax)return false;if(p&&p.volume&&u.volume!==p.volume)return false;const iso=String(u.date_iso||'');if(p&&p.date&&!iso.startsWith(p.date))return false;if(p&&p.year&&!iso.startsWith(String(p.year)))return false;return true;}
  function makeCard(mode,u,a){const toks=authority.tokens(mode,u.id),matched=toks.slice(a.global_start,a.global_start+a.token_len);if(matched.length!==a.token_len)throw new Error('SEARCH-V2.2 canonical token reconstruction mismatch');const parts=sourceParts(matched,documents),first=parts[0],d=documents[first.doc_index],ei=entryById.has(String(u.entry_id))?entryById.get(String(u.entry_id)):d[1],e=entries[ei]||entries[d[1]],matchText=authority.visibleText(parts);return {id:d[0],entry_id:u.entry_id||e[0],stable_ref:d[4],volume:u.volume,title:e[3],date_display:e[4],date_iso:u.date_iso||e[5],text:d[5],is_supplement:d[3]===1,supplement_id:u.supplement_id||null,matchType:'near',near_v22:true,logical_unit_id:u.id,book_order:u.book_order,match_parts:parts,primary_target:{target_kind:'EXACT_SPAN',id:d[0],entry_id:u.entry_id||e[0],stable_ref:d[4],volume:u.volume,supplement_id:u.supplement_id||null,canonical_start:first.canonical_start,canonical_end:first.canonical_end},near_match_text:matchText,edit_operations:a.ops,weighted_distance:a.w,critical_difference_classes:a.critical_classes.slice()};}
  function search(rawOrParsed,options){const opt={mode:'enriched',volMin:0,volMax:0,jesus:false,limit:5,diagnostics:false,...(options||{})},mode=VALID_MODES.has(opt.mode)?opt.mode:'enriched',p=typeof rawOrParsed==='string'?Core.parseQuery(rawOrParsed):(rawOrParsed||{}),q=qtokens(p.lexical||'');if(q.length<3||q.length>14)return {schema:'ldc-search-v22-near-result-r1',version:VERSION,eligible:false,reason:'QUERY_TOKEN_COUNT',query_tokens:q.length,mode,results:[],totalAccepted:0,ambiguous:false,competitive_count:0};const E=threshold(q),cis=candidateUnits(mode,q,E),ans=anchors(mode,q,E),acc=[];for(const ui of cis){const u=modeUnits[mode][ui];if(!scopeAllows(u,p,opt))continue;const a=bestInUnit(u,q,E,ans,{...opt,mode});if(a)acc.push({u,a});}acc.sort((x,y)=>x.a.ops-y.a.ops||x.a.w-y.a.w||x.a.critical_count-y.a.critical_count||x.u.volume-y.u.volume||x.u.book_order-y.u.book_order||x.u.id.localeCompare(y.u.id));const best=acc[0]||null,competitive=best?acc.filter(x=>x.a.ops===best.a.ops&&Math.abs(x.a.w-best.a.w)<1e-9&&x.a.critical_count===best.a.critical_count):[],ambiguous=competitive.length>5,display=(ambiguous?competitive:acc).slice(0,Math.max(1,Math.min(20,Number(opt.limit)||5))),results=display.map(x=>makeCard(mode,x.u,x.a));const out={schema:'ldc-search-v22-near-result-r1',version:VERSION,label:'Formulation proche',eligible:true,query_tokens:q.length,edit_bound:E,mode,results,totalAccepted:acc.length,ambiguous,competitive_count:competitive.length};if(opt.diagnostics)out.diagnostics={candidate_units:cis.length,accepted_units:acc.length,anchors:ans.map(a=>[a.i,a.t,a.df]),ranked:acc.map(x=>({id:x.u.id,ops:x.a.ops,w:x.a.w,critical_count:x.a.critical_count,critical_classes:x.a.critical_classes,window:x.a.window,volume:x.u.volume,book_order:x.u.book_order})),best:best?{id:best.u.id,ops:best.a.ops,w:best.a.w,critical_count:best.a.critical_count}:null};return out;}
  return Object.freeze({VERSION,search,stats:{modes:Object.fromEntries([...VALID_MODES].map(m=>[m,{units:modeUnits[m].length,short_terms:shortTf[m].size,df_terms:df[m].size}]))}});
}
return Object.freeze({VERSION,createNearLayer,qtokens,align});
});
