/* LDC SEARCH-V3 semantic retrieval core R4 — model-agnostic, pre-production.
   Dense-only candidate generation with exact source-mode, Tome, date/year,
   stable-reference and Jesus-span filtering. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.LDCSearchSemanticV3R4=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';const VERSION='ldc-search-v3-semantic-core-r4';
function req(c,m){if(!c)throw new Error(m);}function finite(n){return Number.isFinite(Number(n));}
function norm(a){const o=a instanceof Float32Array?new Float32Array(a):Float32Array.from(a||[]);let s=0;for(const x of o){req(Number.isFinite(x),'SEMANTIC_NONFINITE_VECTOR');s+=x*x;}req(s>0,'SEMANTIC_ZERO_VECTOR');const z=1/Math.sqrt(s);for(let i=0;i<o.length;i++)o[i]*=z;return o;}
function invNorms(v,rows,cols){req(v instanceof Int8Array,'SEMANTIC_INT8_REQUIRED');req(v.length===rows*cols,'SEMANTIC_VECTOR_COUNT_MISMATCH');const o=new Float32Array(rows);for(let r=0;r<rows;r++){let s=0;for(let c=0;c<cols;c++){const x=v[r*cols+c];s+=x*x;}req(s>0,'SEMANTIC_ZERO_CORPUS_ROW');o[r]=1/Math.sqrt(s);}return o;}
function overlap(a,b){if(!a||!b||String(a.unit_id)!==String(b.unit_id))return 0;const s=Math.max(+a.start_word||0,+b.start_word||0),e=Math.min(+a.end_word||0,+b.end_word||0);if(e<=s)return 0;const la=Math.max(1,(+a.end_word||0)-(+a.start_word||0)),lb=Math.max(1,(+b.end_word||0)-(+b.start_word||0));return (e-s)/Math.min(la,lb);}
function heapPush(h,x,k){const less=(a,b)=>a.score<b.score||(a.score===b.score&&a.row>b.row);function up(i){while(i){const p=(i-1)>>1;if(!less(h[i],h[p]))break;[h[i],h[p]]=[h[p],h[i]];i=p;}}function down(i){for(;;){let l=2*i+1,r=l+1,m=i;if(l<h.length&&less(h[l],h[m]))m=l;if(r<h.length&&less(h[r],h[m]))m=r;if(m===i)break;[h[i],h[m]]=[h[m],h[i]];i=m;}}if(h.length<k){h.push(x);up(h.length-1);}else if(x.score>h[0].score||(x.score===h[0].score&&x.row<h[0].row)){h[0]=x;down(0);}}
function bitHas(bits,i){return !!(bits&&bits[i>>3]&(1<<(i&7)));}
function refMatches(p,ref){const r=String(ref||'').trim().toUpperCase();if(!r)return true;const spans=Array.isArray(p&&p.source_spans)?p.source_spans:[];return spans.some(s=>{const x=String(s&&s.stable_ref||'').trim().toUpperCase();return x&&(x===r||x.startsWith(r+'.')||r.startsWith(x+'.'));});}
function dateMatches(p,opt){const d=String(p&&p.date_iso||'');if(opt.dateIso&&d!==String(opt.dateIso))return false;if(opt.year){const y=String(Number(opt.year));if(!/^\d{4}/.test(d)||d.slice(0,4)!==y)return false;}return true;}
function rowAllowed(p,opt,row,jesusBits){if(opt.sourceMode&&String(p.mode)!==String(opt.sourceMode))return false;if(opt.volMin&&+p.volume<+opt.volMin)return false;if(opt.volMax&&+p.volume>+opt.volMax)return false;if(!dateMatches(p,opt))return false;if(opt.stableRef&&!refMatches(p,opt.stableRef))return false;if(opt.jesus){req(jesusBits instanceof Uint8Array,'SEMANTIC_JESUS_MASK_REQUIRED');if(!bitHas(jesusBits,row))return false;}return true;}
function createIndex(payload){
 const P=payload&&payload.passages,dim=+(payload&&payload.dim);req(Array.isArray(P)&&P.length,'SEMANTIC_PASSAGES_REQUIRED');req(Number.isInteger(dim)&&dim>0,'SEMANTIC_INVALID_DIM');
 const ids=new Set();for(const p of P){req(p&&p.passage_id,'SEMANTIC_PASSAGE_ID_REQUIRED');req(!ids.has(p.passage_id),'SEMANTIC_DUPLICATE_PASSAGE_ID');ids.add(p.passage_id);}
 const JB=payload.jesusBits==null?null:payload.jesusBits;if(JB!==null){req(JB instanceof Uint8Array,'SEMANTIC_JESUS_MASK_UINT8_REQUIRED');req(JB.length===Math.ceil(P.length/8),'SEMANTIC_JESUS_MASK_GEOMETRY');}
 let kind=null,V=null,I=null;
 if(payload.vectors instanceof Float32Array){kind='float32';V=payload.vectors;req(V.length===P.length*dim,'SEMANTIC_VECTOR_COUNT_MISMATCH');for(const r of new Set([0,P.length-1,Math.floor(P.length/2)])){let s=0;for(let c=0;c<dim;c++){const x=V[r*dim+c];req(Number.isFinite(x),'SEMANTIC_NONFINITE_CORPUS_VECTOR');s+=x*x;}req(Math.abs(s-1)<.03,'SEMANTIC_CORPUS_VECTOR_NOT_NORMALIZED');}}
 else if(payload.vectors instanceof Int8Array){kind='int8';V=payload.vectors;req(V.length===P.length*dim,'SEMANTIC_VECTOR_COUNT_MISMATCH');I=payload.inverseNorms instanceof Float32Array?payload.inverseNorms:invNorms(V,P.length,dim);req(I.length===P.length,'SEMANTIC_NORM_COUNT_MISMATCH');}
 else throw new Error('SEMANTIC_VECTOR_FORMAT_REQUIRED');
 function score(row,q){let s=0,o=row*dim;for(let c=0;c<dim;c++)s+=V[o+c]*q[c];return kind==='int8'?s*I[row]:s;}
 function denseSearch(qraw,options={}){const opt={candidatePool:160,maxResults:20,collapseThreshold:.5,sourceMode:null,volMin:0,volMax:0,dateIso:null,year:0,stableRef:null,jesus:false,...options};const q=norm(qraw);req(q.length===dim,'SEMANTIC_QUERY_DIM_MISMATCH');const k=Math.max(1,Math.min(P.length,+opt.candidatePool||160)),h=[];let eligibleRows=0;for(let r=0;r<P.length;r++){if(!rowAllowed(P[r],opt,r,JB))continue;eligibleRows++;heapPush(h,{row:r,score:score(r,q)},k);}const ranked=h.sort((a,b)=>b.score-a.score||a.row-b.row).map((x,i)=>({...P[x.row],_row:x.row,dense_score:x.score,dense_rank:i+1}));const collapsed=[];for(const x of ranked){if(collapsed.some(y=>overlap(x,y)>=opt.collapseThreshold))continue;collapsed.push(x);if(collapsed.length>=Math.max(1,+opt.maxResults||20))break;}return {schema:'ldc-search-v3-dense-r4',version:VERSION,index_kind:kind,candidate_population:'DENSE_ONLY',candidate_pool_requested:k,eligible_rows:eligibleRows,dense_candidates:ranked,results:collapsed,filters:{sourceMode:opt.sourceMode||null,volMin:+opt.volMin||0,volMax:+opt.volMax||0,dateIso:opt.dateIso||null,year:+opt.year||0,stableRef:opt.stableRef||null,jesus:!!opt.jesus},diagnostics:{top_score:collapsed[0]?.dense_score??null,top_margin:collapsed.length>1?collapsed[0].dense_score-collapsed[1].dense_score:null,calibration_status:'UNQUALIFIED'}};}
 function rerankDensePool(dense,lexRanks,opt={}){const k=+opt.rrfK||60,dw=+opt.denseWeight||1,lw=+opt.lexWeight||1;const pool=dense.dense_candidates||dense.results||[];const allowed=new Map(pool.map((p,i)=>[String(p.passage_id),{...p,_dr:i+1}]));const L=new Map();for(const [id,r] of Object.entries(lexRanks||{})){if(allowed.has(id)&&finite(r)&&+r>0)L.set(id,+r);}const out=[];for(const [id,p] of allowed){const lr=L.get(id)||null,x={...p,hybrid_score:dw/(k+p._dr)+(lr?lw/(k+lr):0),lexical_rank_within_dense_pool:lr};delete x._dr;out.push(x);}out.sort((a,b)=>b.hybrid_score-a.hybrid_score||a.dense_rank-b.dense_rank);return {schema:'ldc-search-v3-hybrid-r4',candidate_population:'DENSE_ONLY__LEXICAL_CANNOT_IMPORT',results:out};}
 function classify(result,policy){req(policy&&finite(policy.close_min)&&finite(policy.possible_min)&&finite(policy.close_margin)&&finite(policy.abstain_margin),'SEMANTIC_CALIBRATION_POLICY_REQUIRED');const r=result.results||[];if(!r.length)return {state:'abstain',label:'Aucun passage suffisamment proche n’a été identifié.'};const s1=+r[0].dense_score,s2=r.length>1?+r[1].dense_score:-1,m=s1-s2;if(s1>=policy.close_min&&m>=policy.close_margin)return {state:'close',label:'Proche par le sens',s1,s2,margin:m};if(s1>=policy.possible_min&&m>=policy.abstain_margin)return {state:'possible',label:'Quelques pistes possibles',s1,s2,margin:m};return {state:'abstain',label:'Aucun passage suffisamment proche n’a été identifié.',s1,s2,margin:m};}
 return Object.freeze({version:VERSION,indexKind:kind,passages:P.length,dim,jesusMaskBound:JB instanceof Uint8Array,denseSearch,rerankDensePool,classify});
}
return Object.freeze({VERSION,createIndex,norm,invNorms,overlap,bitHas,refMatches,dateMatches});
});
