/* LDC SEARCH-V3 mode-aware qualified-pack registry R5.
   Searchable index bytes are constructed directly from assets that passed the pack guard. */
(function(root){
'use strict';const VERSION='ldc-search-v3-pack-registry-r5';
const MODES=Object.freeze({aflp:'aflp',principal:'aflp',additions:'additions','complément':'additions',complement:'additions',enriched:'enriched',enrichi:'enriched'});
const LABELS=Object.freeze({aflp:'PRINCIPAL',additions:'COMPLÉMENT',enriched:'ENRICHI'});let slots=new Map();
function normMode(m){return MODES[String(m||'').trim().toLowerCase()]||null;}
function unavailable(mode,reason,detail){return {schema:'ldc-semantic-pack-registry-v5',version:VERSION,mode:mode||null,label:mode?LABELS[mode]||mode:null,available:false,calibration_status:'UNQUALIFIED',reason,detail:detail||null};}
function apis(){if(!root.LDCSemanticPackGuardR3)throw new Error('SEMANTIC_PACK_GUARD_R3_REQUIRED');if(!root.LDCSearchSemanticV3R4)throw new Error('SEMANTIC_CORE_R4_REQUIRED');}
function u8(x){if(x instanceof Uint8Array)return new Uint8Array(x.buffer.slice(x.byteOffset,x.byteOffset+x.byteLength));if(x instanceof ArrayBuffer)return new Uint8Array(x.slice(0));return new Uint8Array(x||[]);}
function f32le(bytes,count){const b=u8(bytes);if(b.byteLength!==count*4)throw new Error('FLOAT32_BYTE_GEOMETRY');const v=new DataView(b.buffer,b.byteOffset,b.byteLength),out=new Float32Array(count);for(let i=0;i<count;i++)out[i]=v.getFloat32(i*4,true);return out;}
function parseMetadata(bytes,rows){const text=new TextDecoder('utf-8',{fatal:true}).decode(u8(bytes)),out=[];for(const line of text.split(/\r?\n/)){if(!line.trim())continue;out.push(JSON.parse(line));}if(out.length!==rows)throw new Error('METADATA_ROW_COUNT_MISMATCH');return out;}
async function buildVerifiedIndexPayload(manifest,getBytes,mode){const rows=Number(manifest.index.rows),cols=Number(manifest.index.cols),dtype=manifest.index.dtype;const meta=parseMetadata(await getBytes(manifest.index.metadata_file.path),rows);if(meta.some(p=>normMode(p&&p.mode)!==mode))throw new Error('INDEX_SOURCE_MODE_MISMATCH');let vectors,inverseNorms=null;if(dtype==='int8_row_symmetric'){vectors=new Int8Array(u8(await getBytes(manifest.index.vectors_file.path)).buffer);inverseNorms=f32le(await getBytes(manifest.index.inverse_norms_file.path),rows);}else if(dtype==='float32'){vectors=f32le(await getBytes(manifest.index.vectors_file.path),rows*cols);}else throw new Error('SEMANTIC_RUNTIME_DTYPE_UNSUPPORTED');const jesusBits=u8(await getBytes(manifest.speaker_filter.jesus_mask_file.path));return {passages:meta,dim:cols,vectors,inverseNorms,jesusBits};}
function hashList(xs){return (xs||[]).map(x=>x&&x.sha256||'').join(',');}
function compatKey(entry){const m=entry.manifest;return JSON.stringify({model_sha256:m.model.model_sha256,model_id:m.model.model_id,immutable_revision:m.model.immutable_revision,embedding_dim:m.model.embedding_dim,pooling:m.model.pooling,normalization:m.model.normalization,query_prefix:m.model.query_prefix,passage_prefix:m.model.passage_prefix,tokenizers:hashList(m.model.tokenizer_files),policy_id:m.chunker.policy_id,dtype:m.index.dtype,runtime_engine:m.runtime.engine,runtime_version:m.runtime.version,runtime_files:hashList(m.runtime.files)});}
async function prepare(mode,spec){apis();const m=normMode(mode);if(!m)return {ok:false,status:unavailable(null,'INVALID_SOURCE_MODE',mode)};if(!spec||!spec.manifest||typeof spec.getBytes!=='function'||typeof spec.encodeQuery!=='function')return {ok:false,status:unavailable(m,'BINDING_INPUT_INCOMPLETE')};const mm=normMode(spec.manifest&&spec.manifest.chunker&&spec.manifest.chunker.mode);if(mm!==m)return {ok:false,status:unavailable(m,'PACK_SOURCE_MODE_MISMATCH',{requested:m,manifest:mm})};const v=await root.LDCSemanticPackGuardR3.verifyAssets(spec.manifest,spec.getBytes);if(!v.ok||v.activation!==true)return {ok:false,status:unavailable(m,v.code||'PACK_NOT_QUALIFIED',v)};let payload,index;try{payload=await buildVerifiedIndexPayload(spec.manifest,spec.getBytes,m);index=root.LDCSearchSemanticV3R4.createIndex(payload);}catch(e){return {ok:false,status:unavailable(m,'INDEX_BIND_FAILED',String(e&&e.message||e))};}if(Number(spec.manifest.index.rows)!==Number(index.passages)||Number(spec.manifest.index.cols)!==Number(index.dim))return {ok:false,status:unavailable(m,'INDEX_MANIFEST_GEOMETRY_MISMATCH')};if(!index.jesusMaskBound)return {ok:false,status:unavailable(m,'JESUS_MASK_NOT_BOUND')};return {ok:true,mode:m,entry:{mode:m,manifest:spec.manifest,index,encodeQuery:spec.encodeQuery,verification:v}};}
async function preparePackSet(specByMode,{requireCompatible=true}={}){const entries=[];for(const [mode,spec] of Object.entries(specByMode||{})){const p=await prepare(mode,spec);if(!p.ok)return {ok:false,activation:false,code:'PACK_SET_REJECTED',failed_mode:normMode(mode)||mode,detail:p.status};entries.push(p);}if(!entries.length)return {ok:false,activation:false,code:'PACK_SET_EMPTY'};const modes=new Set(entries.map(x=>x.mode));if(modes.size!==entries.length)return {ok:false,activation:false,code:'PACK_SET_DUPLICATE_MODE'};if(requireCompatible){const keys=new Set(entries.map(x=>compatKey(x.entry)));if(keys.size!==1)return {ok:false,activation:false,code:'PACK_SET_INCOMPATIBLE_TUPLES'};}return {ok:true,activation:false,prepared:true,version:VERSION,modes:entries.map(x=>x.mode),_entries:entries};}
function commitPreparedSet(token,{replaceAll=false}={}){if(!token||token.ok!==true||token.prepared!==true||!Array.isArray(token._entries))return {ok:false,activation:false,code:'INVALID_PREPARED_TOKEN'};const next=replaceAll?new Map():new Map(slots);for(const p of token._entries)next.set(p.mode,p.entry);slots=next;return {ok:true,activation:true,version:VERSION,modes:token._entries.map(x=>x.mode),available_modes:[...slots.keys()]};}
async function bindPackSet(specByMode,opts={}){const p=await preparePackSet(specByMode,opts);if(!p.ok)return p;return commitPreparedSet(p,{replaceAll:!!opts.replaceAll});}
async function bindModePack(mode,spec){const p=await preparePackSet({[mode]:spec},{requireCompatible:false});if(!p.ok)return p.detail||unavailable(normMode(mode),'PACK_NOT_QUALIFIED');commitPreparedSet(p,{replaceAll:false});return status(normMode(mode));}
function unbindMode(mode){const m=normMode(mode);if(m)slots.delete(m);return status(m);}
function unbindAll(){slots=new Map();return status();}
function status(mode){const m=mode==null?null:normMode(mode);if(mode!=null&&!m)return unavailable(null,'INVALID_SOURCE_MODE',mode);if(m){const e=slots.get(m);if(!e)return unavailable(m,'PACK_NOT_INSTALLED_OR_QUALIFIED');return {schema:'ldc-semantic-pack-registry-v5',version:VERSION,mode:m,label:LABELS[m],available:true,calibration_status:'QUALIFIED',pack_id:e.manifest.pack_id||null,model_id:e.manifest.model&&e.manifest.model.model_id||null,chunker_id:e.manifest.chunker&&e.manifest.chunker.policy_id||null,jesus_filter_bound:true,verified_files:e.verification.verified_files||0};}const modes={};for(const x of ['aflp','additions','enriched'])modes[x]=status(x);return {schema:'ldc-semantic-pack-registry-v5',version:VERSION,available_modes:[...slots.keys()],modes};}
async function search(query,options={}){const m=normMode(options.sourceMode);if(!m)throw new Error('SEMANTIC_SOURCE_MODE_REQUIRED');const e=slots.get(m);if(!e)throw new Error('SEMANTIC_PACK_NOT_AVAILABLE_FOR_MODE');const q=String(query||'').trim();if(!q)throw new Error('SEMANTIC_QUERY_EMPTY');const vec=await e.encodeQuery(q,e.manifest.model);const dense=e.index.denseSearch(vec,{candidatePool:options.candidatePool||160,maxResults:options.maxResults||20,collapseThreshold:options.collapseThreshold||.5,sourceMode:m,volMin:options.volMin||0,volMax:options.volMax||0,dateIso:options.dateIso||null,year:options.year||0,stableRef:options.stableRef||null,jesus:!!options.jesus});const policy=e.manifest.calibration.threshold_policy;const confidence=e.index.classify(dense,policy);return {schema:'ldc-search-v3-result-r4',version:VERSION,query:q,source_mode:m,candidate_population:'DENSE_ONLY',filters:dense.filters,confidence,results:confidence.state==='abstain'?[]:dense.results,diagnostics:dense.diagnostics,pack_id:e.manifest.pack_id||null};}
root.LDCSemanticPackRegistryV5=Object.freeze({VERSION,normMode,buildVerifiedIndexPayload,preparePackSet,commitPreparedSet,bindModePack,bindPackSet,unbindMode,unbindAll,status,search});
})(typeof globalThis!=='undefined'?globalThis:this);
