/* LDC SEARCH-V3 semantic-pack lifecycle R5.
   Atomic activation pointers, staged install, rollback on verification/bind failure,
   per-mode removal, startup restore. Storage is abstract; IndexedDB + memory references included. */
(function(root){
'use strict';const VERSION='ldc-search-v3-pack-lifecycle-r5';
function reqRegistry(){const R=root.LDCSemanticPackRegistryV5;if(!R)throw new Error('SEMANTIC_PACK_REGISTRY_R5_REQUIRED');return R;}
function u8(x){if(x instanceof Uint8Array)return new Uint8Array(x);if(x instanceof ArrayBuffer)return new Uint8Array(x.slice(0));return new Uint8Array(x||[]);}
let seq=0;function stageKey(mode,manifest){return `${String(manifest&&manifest.pack_id||'pack')}::${String(mode)}::stage${++seq}`;}
function createMemoryStore(){const packs=new Map(),assets=new Map(),active=new Map();return Object.freeze({
 async putManifest(k,m){packs.set(k,JSON.parse(JSON.stringify(m)));},async getManifest(k){const m=packs.get(k);return m?JSON.parse(JSON.stringify(m)):null;},
 async putAsset(k,p,b){assets.set(k+'|'+p,u8(b));},async getAsset(k,p){const b=assets.get(k+'|'+p);if(!b)throw new Error('PACK_ASSET_NOT_FOUND:'+p);return new Uint8Array(b);},
 async commitActiveSet(map){for(const [mode,key] of Object.entries(map||{})){if(key==null)active.delete(mode);else active.set(mode,key);}},async getActiveKey(mode){return active.get(mode)||null;},async getActiveMap(){return Object.fromEntries(active)},
 async deletePack(k){packs.delete(k);for(const x of [...assets.keys()])if(x.startsWith(k+'|'))assets.delete(x);},
 async listPackKeys(){return [...packs.keys()]},_debug(){return {packs:[...packs.keys()],active:Object.fromEntries(active),asset_count:assets.size};}
 });}
function idbReq(r){return new Promise((res,rej)=>{r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error||new Error('IDB_REQUEST_FAILED'));});}
function openDb(name='ldc-search-v3-semantic-packs-r1'){if(!root.indexedDB)throw new Error('INDEXEDDB_UNAVAILABLE');return new Promise((res,rej)=>{const r=root.indexedDB.open(name,1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('packs'))db.createObjectStore('packs');if(!db.objectStoreNames.contains('assets'))db.createObjectStore('assets');if(!db.objectStoreNames.contains('meta'))db.createObjectStore('meta');};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error||new Error('IDB_OPEN_FAILED'));});}
async function createIndexedDBStore(name){const db=await openDb(name);function tx(store,mode='readonly'){return db.transaction(store,mode).objectStore(store);}return Object.freeze({
 async putManifest(k,m){await idbReq(tx('packs','readwrite').put(JSON.parse(JSON.stringify(m)),k));},async getManifest(k){return (await idbReq(tx('packs').get(k)))||null;},
 async putAsset(k,p,b){await idbReq(tx('assets','readwrite').put(u8(b),k+'|'+p));},async getAsset(k,p){const x=await idbReq(tx('assets').get(k+'|'+p));if(!x)throw new Error('PACK_ASSET_NOT_FOUND:'+p);return u8(x);},
 async commitActiveSet(map){await new Promise((res,rej)=>{const t=db.transaction('meta','readwrite'),s=t.objectStore('meta');for(const [m,k] of Object.entries(map||{})){if(k==null)s.delete('active:'+m);else s.put(k,'active:'+m);}t.oncomplete=()=>res();t.onerror=()=>rej(t.error||new Error('IDB_COMMIT_ACTIVE_FAILED'));t.onabort=()=>rej(t.error||new Error('IDB_COMMIT_ACTIVE_ABORTED'));});},
 async getActiveKey(mode){return (await idbReq(tx('meta').get('active:'+mode)))||null;},async getActiveMap(){const out={};for(const m of ['aflp','additions','enriched']){const k=await this.getActiveKey(m);if(k)out[m]=k;}return out;},
 async listPackKeys(){return (await idbReq(tx('packs').getAllKeys())).map(String);},async deletePack(k){const keys=(await idbReq(tx('assets').getAllKeys())).map(String).filter(x=>x.startsWith(k+'|'));await new Promise((res,rej)=>{const t=db.transaction(['packs','assets'],'readwrite'),ps=t.objectStore('packs'),as=t.objectStore('assets');ps.delete(k);for(const key of keys)as.delete(key);t.oncomplete=()=>res();t.onerror=()=>rej(t.error||new Error('IDB_DELETE_PACK_FAILED'));t.onabort=()=>rej(t.error||new Error('IDB_DELETE_PACK_ABORTED'));});},close(){db.close();}
 });}
async function stageOne(mode,spec,store){const R=reqRegistry(),m=R.normMode(mode),G=root.LDCSemanticPackGuardR3;if(!m)throw new Error('INVALID_SOURCE_MODE');if(!G)throw new Error('SEMANTIC_PACK_GUARD_R3_REQUIRED');if(!spec||!spec.manifest||typeof spec.fetchAsset!=='function'||typeof spec.createEncoder!=='function')throw new Error('INSTALL_SPEC_INCOMPLETE');const key=stageKey(m,spec.manifest);await store.putManifest(key,spec.manifest);try{for(const f of (spec.manifest.files||[])){const b=await spec.fetchAsset(f.path,spec.manifest);await store.putAsset(key,f.path,b);}const getBytes=p=>store.getAsset(key,p);const verified=await G.verifyAssets(spec.manifest,getBytes);if(!verified.ok||verified.activation!==true)throw new Error('PACK_STAGE_VERIFY_FAILED:'+String(verified.code||''));const encodeQuery=await spec.createEncoder({manifest:spec.manifest,getBytes,mode:m});if(typeof encodeQuery!=='function')throw new Error('ENCODER_FACTORY_INVALID');return {mode:m,key,manifest:spec.manifest,getBytes,encodeQuery};}catch(e){await store.deletePack(key).catch(()=>{});throw e;}}
async function installPackSet(specByMode,{store,requireCompatible=true,retainPrevious=true}={}){if(!store)throw new Error('PACK_STORE_REQUIRED');const R=reqRegistry(),staged=[],previous=await store.getActiveMap();try{for(const [mode,spec] of Object.entries(specByMode||{}))staged.push(await stageOne(mode,spec,store));if(!staged.length)throw new Error('PACK_SET_EMPTY');const bindSpecs=Object.fromEntries(staged.map(x=>[x.mode,{manifest:x.manifest,getBytes:x.getBytes,encodeQuery:x.encodeQuery}]));const prepared=await R.preparePackSet(bindSpecs,{requireCompatible});if(!prepared.ok)throw new Error('PACK_REGISTRY_PREPARE_FAILED:'+String(prepared.code||prepared.detail&&prepared.detail.reason||''));const activeMap={};for(const x of staged)activeMap[x.mode]=x.key;await store.commitActiveSet(activeMap);const committed=R.commitPreparedSet(prepared,{replaceAll:false});if(!committed.ok){const rollback={};for(const x of staged)rollback[x.mode]=previous[x.mode]||null;await store.commitActiveSet(rollback);throw new Error('PACK_REGISTRY_COMMIT_FAILED:'+String(committed.code||''));}if(!retainPrevious){for(const [mode,key] of Object.entries(previous)){if(activeMap[mode]&&key!==activeMap[mode])await store.deletePack(key).catch(()=>{});}}return {ok:true,version:VERSION,installed_modes:staged.map(x=>x.mode),active_keys:activeMap,previous_keys:previous};}catch(e){for(const x of staged)await store.deletePack(x.key).catch(()=>{});return {ok:false,version:VERSION,error:String(e&&e.message||e),active_keys:await store.getActiveMap()};}}
async function restoreActive({store,encoderFactoryByPack}={}){if(!store||typeof encoderFactoryByPack!=='function')throw new Error('RESTORE_INPUT_INCOMPLETE');const R=reqRegistry(),active=await store.getActiveMap(),out={};for(const [mode,key] of Object.entries(active)){const manifest=await store.getManifest(key);if(!manifest){R.unbindMode(mode);await store.commitActiveSet({[mode]:null}).catch(()=>{});out[mode]={ok:false,reason:'ACTIVE_MANIFEST_MISSING'};continue;}const getBytes=p=>store.getAsset(key,p);try{const encodeQuery=await encoderFactoryByPack({mode,key,manifest,getBytes});const s=await R.bindModePack(mode,{manifest,getBytes,encodeQuery});out[mode]={ok:!!s.available,status:s};if(!s.available){R.unbindMode(mode);await store.commitActiveSet({[mode]:null});}}catch(e){R.unbindMode(mode);await store.commitActiveSet({[mode]:null}).catch(()=>{});out[mode]={ok:false,reason:String(e&&e.message||e)};}}return {version:VERSION,modes:out};}
async function removeMode(mode,{store,deleteBytes=true}={}){if(!store)throw new Error('PACK_STORE_REQUIRED');const R=reqRegistry(),m=R.normMode(mode);if(!m)throw new Error('INVALID_SOURCE_MODE');const key=await store.getActiveKey(m);await store.commitActiveSet({[m]:null});R.unbindMode(m);if(deleteBytes&&key)await store.deletePack(key);return {ok:true,mode:m,removed_key:key||null};}
root.LDCSemanticPackLifecycleR5=Object.freeze({VERSION,createMemoryStore,createIndexedDBStore,installPackSet,restoreActive,removeMode});
})(typeof globalThis!=='undefined'?globalThis:this);
