/* LDC SEARCH-V3 current-corpus registry R6.
   Qualified packs only; dense + BM25 RRF60; hybrid confidence may abstain. */
(function(root){
'use strict';const VERSION='ldc-search-v3-pack-registry-r6';
const MODES=Object.freeze({aflp:'aflp',principal:'aflp',additions:'additions','complément':'additions',complement:'additions',enriched:'enriched',enrichi:'enriched'});
const LABELS=Object.freeze({aflp:'PRINCIPAL',additions:'COMPLÉMENT',enriched:'ENRICHI'});let slots=new Map();
function normMode(m){return MODES[String(m||'').trim().toLowerCase()]||null;}
function unavailable(mode,reason,detail){return {schema:'ldc-semantic-pack-registry-v6',version:VERSION,mode:mode||null,label:mode?LABELS[mode]||mode:null,available:false,calibration_status:'UNQUALIFIED',reason,detail:detail||null};}
function apis(){if(!root.LDCSemanticPackGuardR4)throw new Error('SEMANTIC_PACK_GUARD_R4_REQUIRED');if(!root.LDCSearchSemanticV3R4)throw new Error('SEMANTIC_CORE_R4_REQUIRED');if(!root.LDCSemanticHybridR6)throw new Error('SEMANTIC_HYBRID_R6_REQUIRED');}
function u8(x){if(x instanceof Uint8Array)return new Uint8Array(x.buffer.slice(x.byteOffset,x.byteOffset+x.byteLength));if(x instanceof ArrayBuffer)return new Uint8Array(x.slice(0));return new Uint8Array(x||[]);}
function f32le(bytes,count){const b=u8(bytes);if(b.byteLength!==count*4)throw new Error('FLOAT32_BYTE_GEOMETRY');const v=new DataView(b.buffer,b.byteOffset,b.byteLength),out=new Float32Array(count);for(let i=0;i<count;i++)out[i]=v.getFloat32(i*4,true);return out;}
function parseMetadata(bytes,rows){const text=new TextDecoder('utf-8',{fatal:true}).decode(u8(bytes)),out=[];for(const line of text.split(/\r?\n/)){if(!line.trim())continue;out.push(JSON.parse(line));}if(out.length!==rows)throw new Error('METADATA_ROW_COUNT_MISMATCH');return out;}
async function buildVerifiedPayload(manifest,getBytes,mode){const rows=Number(manifest.index.rows),cols=Number(manifest.index.cols),meta=parseMetadata(await getBytes(manifest.index.metadata_file.path),rows);if(meta.some(p=>normMode(p&&p.mode)!==mode))throw new Error('INDEX_SOURCE_MODE_MISMATCH');const vb=u8(await getBytes(manifest.index.vectors_file.path)),vectors=new Int8Array(vb.buffer,vb.byteOffset,vb.byteLength),inverseNorms=f32le(await getBytes(manifest.index.inverse_norms_file.path),rows),jesusBits=u8(await getBytes(manifest.speaker_filter.jesus_mask_file.path));return {passages:meta,dim:cols,vectors,inverseNorms,jesusBits};}
function hashList(xs){return (xs||[]).map(x=>x&&x.sha256||'').join(',');}
function compatKey(entry){const m=entry.manifest;return JSON.stringify({model_sha256:m.model.model_sha256,model_id:m.model.model_id,immutable_revision:m.model.immutable_revision,embedding_dim:m.model.embedding_dim,pooling:m.model.pooling,normalization:m.model.normalization,query_prefix:m.model.query_prefix,passage_prefix:m.model.passage_prefix,tokenizers:hashList(m.model.tokenizer_files),policy_id:m.chunker.policy_id,dtype:m.index.dtype,retrieval:m.retrieval&&m.retrieval.id});}
async function prepare(mode,spec){apis();const m=normMode(mode);if(!m)return {ok:false,status:unavailable(null,'INVALID_SOURCE_MODE',mode)};if(!spec||!spec.manifest||typeof spec.getBytes!=='function'||typeof spec.encodeQuery!=='function')return {ok:false,status:unavailable(m,'BINDING_INPUT_INCOMPLETE')};if(m!=='enriched')return {ok:false,status:unavailable(m,'CURRENT_PACK_SUPPORTS_NORMAL_READING_ONLY')};const v=await root.LDCSemanticPackGuardR4.verifyAssets(spec.manifest,spec.getBytes);if(!v.ok||v.activation!==true)return {ok:false,status:unavailable(m,v.code||'PACK_NOT_QUALIFIED',v)};let payload,index,bm25,passageById;try{payload=await buildVerifiedPayload(spec.manifest,spec.getBytes,m);index=root.LDCSearchSemanticV3R4.createIndex(payload);bm25=root.LDCSemanticHybridR6.buildBm25(payload.passages,payload.jesusBits);passageById=new Map(payload.passages.map(p=>[String(p.passage_id),p]));}catch(e){return {ok:false,status:unavailable(m,'INDEX_BIND_FAILED',String(e&&e.message||e))};}if(Number(spec.manifest.index.rows)!==Number(index.passages)||Number(spec.manifest.index.cols)!==Number(index.dim)||bm25.N!==index.passages||passageById.size!==index.passages)return {ok:false,status:unavailable(m,'INDEX_MANIFEST_GEOMETRY_MISMATCH')};if(!index.jesusMaskBound)return {ok:false,status:unavailable(m,'JESUS_MASK_NOT_BOUND')};return {ok:true,mode:m,entry:{mode:m,manifest:spec.manifest,index,bm25,passageById,encodeQuery:spec.encodeQuery,verification:v}};}
async function preparePackSet(specByMode,{requireCompatible=true}={}){const entries=[];for(const[mode,spec]of Object.entries(specByMode||{})){const p=await prepare(mode,spec);if(!p.ok)return {ok:false,activation:false,code:'PACK_SET_REJECTED',failed_mode:normMode(mode)||mode,detail:p.status};entries.push(p);}if(!entries.length)return {ok:false,activation:false,code:'PACK_SET_EMPTY'};const modes=new Set(entries.map(x=>x.mode));if(modes.size!==entries.length)return {ok:false,activation:false,code:'PACK_SET_DUPLICATE_MODE'};if(requireCompatible){const keys=new Set(entries.map(x=>compatKey(x.entry)));if(keys.size!==1)return {ok:false,activation:false,code:'PACK_SET_INCOMPATIBLE_TUPLES'};}return {ok:true,activation:false,prepared:true,version:VERSION,modes:entries.map(x=>x.mode),_entries:entries};}
function commitPreparedSet(token,{replaceAll=false}={}){if(!token||token.ok!==true||token.prepared!==true||!Array.isArray(token._entries))return {ok:false,activation:false,code:'INVALID_PREPARED_TOKEN'};const next=replaceAll?new Map():new Map(slots);for(const p of token._entries)next.set(p.mode,p.entry);slots=next;return {ok:true,activation:true,version:VERSION,modes:token._entries.map(x=>x.mode),available_modes:[...slots.keys()]};}
async function bindPackSet(specByMode,opts={}){const p=await preparePackSet(specByMode,opts);if(!p.ok)return p;return commitPreparedSet(p,{replaceAll:!!opts.replaceAll});}
async function bindModePack(mode,spec){const p=await preparePackSet({[mode]:spec},{requireCompatible:false});if(!p.ok)return p.detail||unavailable(normMode(mode),'PACK_NOT_QUALIFIED');commitPreparedSet(p,{replaceAll:false});return status(normMode(mode));}
function unbindMode(mode){const m=normMode(mode);if(m)slots.delete(m);return status(m);}function unbindAll(){slots=new Map();return status();}
function status(mode){const m=mode==null?null:normMode(mode);if(mode!=null&&!m)return unavailable(null,'INVALID_SOURCE_MODE',mode);if(m){const e=slots.get(m);if(!e)return unavailable(m,'PACK_NOT_INSTALLED_OR_QUALIFIED');return {schema:'ldc-semantic-pack-registry-v6',version:VERSION,mode:m,label:LABELS[m],available:true,calibration_status:'QUALIFIED',pack_id:e.manifest.pack_id||null,model_id:e.manifest.model&&e.manifest.model.model_id||null,chunker_id:e.manifest.chunker&&e.manifest.chunker.policy_id||null,retrieval_id:e.manifest.retrieval&&e.manifest.retrieval.id||null,calibration_policy_id:e.manifest.calibration&&e.manifest.calibration.hybrid_policy&&e.manifest.calibration.hybrid_policy.policy_id||null,jesus_filter_bound:true,verified_files:e.verification.verified_files||0};}const modes={};for(const x of['aflp','additions','enriched'])modes[x]=status(x);return {schema:'ldc-semantic-pack-registry-v6',version:VERSION,available_modes:[...slots.keys()],modes};}
async function search(query,options={}){const m=normMode(options.sourceMode);if(m!=='enriched')throw new Error('SEMANTIC_CURRENT_PACK_REQUIRES_ENRICHED_MODE');const e=slots.get(m);if(!e)throw new Error('SEMANTIC_PACK_NOT_AVAILABLE_FOR_MODE');const q=String(query||'').trim();if(!q)throw new Error('SEMANTIC_QUERY_EMPTY');const vec=await e.encodeQuery(q,e.manifest.model),r=e.manifest.retrieval,opt={sourceMode:m,volMin:options.volMin||0,volMax:options.volMax||0,dateIso:options.dateIso||null,year:options.year||0,stableRef:options.stableRef||null,jesus:!!options.jesus};const dense=e.index.denseSearch(vec,{...opt,candidatePool:r.dense_candidate_depth,maxResults:r.dense_candidate_depth,collapseThreshold:.5}),sparse=root.LDCSemanticHybridR6.bm25Search(e.bm25,q,{...opt,maxCandidates:r.bm25_candidate_depth}),fused=root.LDCSemanticHybridR6.fuse(dense.dense_candidates,sparse.results,{maxResults:r.output_depth}),confidence=root.LDCSemanticHybridR6.classify(fused,e.manifest.calibration.hybrid_policy),enriched=fused.map(x=>Object.assign({},e.passageById.get(String(x.passage_id))||{},x));return {schema:'ldc-search-v3-hybrid-result-r6',version:VERSION,query:q,source_mode:m,candidate_population:'DENSE_96_72_PLUS_BM25_96_72_RRF60',filters:dense.filters,confidence,results:confidence.state==='abstain'?[]:enriched,diagnostics:{dense_candidates:dense.dense_candidates.length,bm25_candidates:sparse.results.length,hybrid_features:confidence.features},pack_id:e.manifest.pack_id||null};}
root.LDCSemanticPackRegistryR6=Object.freeze({VERSION,normMode,buildVerifiedPayload,preparePackSet,commitPreparedSet,bindModePack,bindPackSet,unbindMode,unbindAll,status,search});
})(typeof globalThis!=='undefined'?globalThis:this);
