/* LDC SEARCH-V3 hybrid retrieval R6.
   Exact successor of protected PLS v1.5 BM25 + equal RRF60 fusion, with manifest-driven abstention. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.LDCSemanticHybridR6=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const VERSION='ldc-search-v3-hybrid-r6',K1=1.2,B=0.75,RRF_K=60,SOURCE_DEPTH=160,OUTPUT_DEPTH=20;
function req(c,m){if(!c)throw new Error(m);}
function normalise(s){s=String(s||'').toLowerCase();const repl=[['é','e'],['è','e'],['ê','e'],['ë','e'],['à','a'],['â','a'],['î','i'],['ï','i'],['ô','o'],['ö','o'],['ù','u'],['û','u'],['ü','u'],['ç','c'],['œ','oe'],['æ','ae']];for(const[a,b]of repl)s=s.split(a).join(b);return s.replace(/\u00a0|\u202f/g,' ').replace(/[‘’‚‛]/g,' ').replace(/[-–—]/g,' ').replace(/[^A-Za-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();}
function terms(s){return normalise(s).split(' ').filter(t=>t&&t.length>=3);}
function bitHas(bits,i){return !!(bits&&bits[i>>3]&(1<<(i&7)));}
function refMatches(p,ref){const r=String(ref||'').trim().toUpperCase();if(!r)return true;return (Array.isArray(p&&p.source_spans)?p.source_spans:[]).some(s=>{const x=String(s&&s.stable_ref||'').trim().toUpperCase();return x&&(x===r||x.startsWith(r+'.')||r.startsWith(x+'.'));});}
function dateMatches(p,opt){const d=String(p&&p.date_iso||'');if(opt.dateIso&&d!==String(opt.dateIso))return false;if(opt.year){const y=String(Number(opt.year));if(!/^\d{4}/.test(d)||d.slice(0,4)!==y)return false;}return true;}
function rowAllowed(p,opt,row,jesusBits){if(opt.sourceMode&&String(p.mode)!==String(opt.sourceMode))return false;if(opt.volMin&&+p.volume<+opt.volMin)return false;if(opt.volMax&&+p.volume>+opt.volMax)return false;if(!dateMatches(p,opt))return false;if(opt.stableRef&&!refMatches(p,opt.stableRef))return false;if(opt.jesus){req(jesusBits instanceof Uint8Array,'HYBRID_JESUS_MASK_REQUIRED');if(!bitHas(jesusBits,row))return false;}return true;}
function buildBm25(passages,jesusBits=null){req(Array.isArray(passages)&&passages.length,'HYBRID_PASSAGES_REQUIRED');const N=passages.length,dl=new Int32Array(N),tmp=new Map();let total=0;for(let i=0;i<N;i++){const ts=terms(passages[i]&&passages[i].text);dl[i]=ts.length;total+=ts.length;const c=new Map();for(const t of ts)c.set(t,(c.get(t)||0)+1);for(const[t,tf]of c){let a=tmp.get(t);if(!a){a=[];tmp.set(t,a);}a.push(i,tf);}}const postings=new Map();for(const[t,a]of tmp){const n=a.length/2,ids=new Int32Array(n),tfs=new Float32Array(n);for(let j=0;j<n;j++){ids[j]=a[j*2];tfs[j]=a[j*2+1];}postings.set(t,{ids,tfs});}return Object.freeze({version:VERSION,passages,N,dl,avgdl:total/N,postings,vocab:postings.size,jesusBits});}
function bm25Search(index,qtext,options={}){const opt={sourceMode:null,volMin:0,volMax:0,dateIso:null,year:0,stableRef:null,jesus:false,maxCandidates:SOURCE_DEPTH,...options},scores=new Float32Array(index.N),q=[...new Set(terms(qtext))];for(const t of q){const p=index.postings.get(t);if(!p)continue;const df=p.ids.length,idf=Math.log(1+(index.N-df+.5)/(df+.5));for(let j=0;j<df;j++){const i=p.ids[j];if(!rowAllowed(index.passages[i],opt,i,index.jesusBits))continue;const tf=p.tfs[j],den=tf+K1*(1-B+B*index.dl[i]/index.avgdl);scores[i]=Math.fround(scores[i]+Math.fround(idf*tf*(K1+1)/den));}}const rows=[];for(let i=0;i<index.N;i++)if(scores[i]>0&&rowAllowed(index.passages[i],opt,i,index.jesusBits))rows.push(i);rows.sort((a,b)=>scores[b]-scores[a]||a-b);const top=rows.slice(0,Math.max(1,Math.min(SOURCE_DEPTH,+opt.maxCandidates||SOURCE_DEPTH)));return {schema:'ldc-search-v3-bm25-r6',source_mode:opt.sourceMode||null,eligible_rows:index.N,positive_score_candidates:rows.length,results:top.map((i,k)=>Object.assign({},index.passages[i],{_row:i,bm25_score:scores[i],bm25_rank:k+1}))};}
function uniqueEntryRows(rows){const u=[],seen=new Set();for(const row of rows||[]){const eid=row&&(row.entry_id||row.id);if(!eid||seen.has(String(eid)))continue;seen.add(String(eid));u.push({entry_rank:u.length+1,entry_id:String(eid),row});}return u;}
function fuse(denseCandidates,bm25Results,options={}){const maxResults=Math.max(1,Math.min(OUTPUT_DEPTH,+options.maxResults||OUTPUT_DEPTH)),D=uniqueEntryRows(denseCandidates),Bv=uniqueEntryRows(bm25Results),scores=new Map(),prov=new Map(),ex=new Map();for(const[channel,rows]of[['dense_96_72',D],['bm25_96_72',Bv]])for(const x of rows){scores.set(x.entry_id,(scores.get(x.entry_id)||0)+1/(RRF_K+x.entry_rank));if(!prov.has(x.entry_id))prov.set(x.entry_id,{});prov.get(x.entry_id)[channel]=x.entry_rank;if(!ex.has(x.entry_id))ex.set(x.entry_id,x.row);}const ids=[...scores.keys()].sort((a,b)=>scores.get(b)-scores.get(a)||(a<b?-1:(a>b?1:0)));return ids.slice(0,maxResults).map((eid,i)=>{const r=ex.get(eid);return {rank:i+1,entry_id:eid,rrf60_score:scores.get(eid),source_ranks:prov.get(eid),dense_score:Number.isFinite(Number(r.dense_score))?Number(r.dense_score):null,bm25_score:Number.isFinite(Number(r.bm25_score))?Number(r.bm25_score):null,volume:r.volume,date_iso:r.date_iso||r.date||null,title:r.title,text:r.text,passage_id:r.passage_id||null};});}
function features(rows){const r=rows||[],top=r[0]||null,second=r[1]||null;if(!top)return {top_rrf:0,second_rrf:0,rrf_margin:0,top_dense_score:null,second_dense_score:null,channels:0,dense_rank:null,bm25_rank:null};const sr=top.source_ranks||{},channels=(Number.isFinite(Number(sr.dense_96_72))?1:0)+(Number.isFinite(Number(sr.bm25_96_72))?1:0),s1=Number(top.rrf60_score)||0,s2=second?(Number(second.rrf60_score)||0):0;return {top_rrf:s1,second_rrf:s2,rrf_margin:s1-s2,top_dense_score:Number.isFinite(Number(top.dense_score))?Number(top.dense_score):null,second_dense_score:second&&Number.isFinite(Number(second.dense_score))?Number(second.dense_score):null,channels,dense_rank:Number.isFinite(Number(sr.dense_96_72))?Number(sr.dense_96_72):null,bm25_rank:Number.isFinite(Number(sr.bm25_96_72))?Number(sr.bm25_96_72):null};}
function classify(rows,policy){req(policy&&policy.policy_id==='HYBRID_DENSE_ABSTENTION_V1','HYBRID_CALIBRATION_POLICY_REQUIRED');req(policy.close_enabled===false,'HYBRID_CLOSE_MUST_REMAIN_DISABLED');req(Number.isFinite(Number(policy.possible_min_dense)),'HYBRID_CALIBRATION_VALUE_possible_min_dense');req(Number.isFinite(Number(policy.possible_min_channels)),'HYBRID_CALIBRATION_VALUE_possible_min_channels');const f=features(rows);if(!rows||!rows.length||f.top_dense_score==null)return {state:'abstain',label:'Aucun passage suffisamment proche n’a été identifié.',features:f};const possible=f.top_dense_score>=+policy.possible_min_dense&&f.channels>=+policy.possible_min_channels;if(possible)return {state:'possible',label:'Quelques pistes possibles',features:f};return {state:'abstain',label:'Aucun passage suffisamment proche n’a été identifié.',features:f};}
return Object.freeze({VERSION,K1,B,RRF_K,SOURCE_DEPTH,OUTPUT_DEPTH,normalise,terms,buildBm25,bm25Search,uniqueEntryRows,fuse,features,classify});
});
